/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache 2.0
 */

#include "gd32-af.h"

/* ANALOG */
#define ANALOG_PA2 \
	GD32_PINMUX_AF('A', 2, ANALOG)
#define ANALOG_PA3 \
	GD32_PINMUX_AF('A', 3, ANALOG)

/* PERIPH0_SIGA */
#define PERIPH0_SIGA_PA2 \
	GD32_PINMUX_AF('A', 2, AF10)

/* PERIPH1_SIGB */
#define PERIPH1_SIGB_PA3 \
	GD32_PINMUX_AF('A', 3, AF6)

/* PERIPH2_SIGA */
#define PERIPH2_SIGA_PA2 \
	GD32_PINMUX_AF('A', 2, AF8)
#define PERIPH2_SIGA_PA3 \
	GD32_PINMUX_AF('A', 3, AF8)

/* PERIPH3_SIGA */
#define PERIPH3_SIGA_PA2 \
	GD32_PINMUX_AF('A', 2, AF13)
#define PERIPH3_SIGA_PA3 \
	GD32_PINMUX_AF('A', 3, AF12)
