/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_trng.h>
#elif defined(CONFIG_SOC_SERIES_GD32L23X)
#include <gd32l23x_trng.h>
#endif
