/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32A50X)
#include <gd32a50x_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32E50X)
#include <gd32e50x_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32F403)
#include <gd32f403_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32VF103)
#include <gd32vf103_can.h>
#endif
