/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32A50X)
#include <gd32a50x_timer.h>
#elif defined(CONFIG_SOC_SERIES_GD32E10X)
#include <gd32e10x_timer.h>
#elif defined(CONFIG_SOC_SERIES_GD32E50X)
#include <gd32e50x_timer.h>
#elif defined(CONFIG_SOC_SERIES_GD32F3X0)
#include <gd32f3x0_timer.h>
#elif defined(CONFIG_SOC_SERIES_GD32F403)
#include <gd32f403_timer.h>
#elif defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_timer.h>
#elif defined(CONFIG_SOC_SERIES_GD32L23X)
#include <gd32l23x_timer.h>
#elif defined(CONFIG_SOC_SERIES_GD32VF103)
#include <gd32vf103_timer.h>
#endif
