/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_ipa.h>
#elif defined(CONFIG_SOC_SERIES_GD32F5XX)
#include <gd32f5xx_ipa.h>
#endif
