/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <drv_usb_dev.h>
#include <drv_usb_regs.h>
#include <drv_usbd_int.h>
#include <drv_usbh_int.h>
#include <drv_usb_core.h>
#include <drv_usb_hw.h>
#include <drv_usb_host.h>
#endif
