/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32E10X)
#include <gd32e10x_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32F3X0)
#include <gd32f3x0_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32F403)
#include <gd32f403_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32VF103)
#include <gd32vf103_gpio.h>
#endif
