/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_adc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F8XX)
#include <gd32f8xx_adc.h>
#endif
