name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/scripts
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - name: Checkout the code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          pip3 install -r scripts/requirements.txt
          pip3 install -r scripts/requirements-test.txt
          pip3 install -r scripts/requirements-dev.txt
      - name: lint scripts
        run: flake8 --config scripts/.flake8 scripts
      - name: run script tests
        run: |
          pytest scripts/tests \
            --cov=scripts \
            --cov-config scripts/.coveragerc \
            --cov-report term \
            -vv
